// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsW2O4Fd0rbHWQqhTM2Ft7bgeI7RLSG6M',
    appId: '1:933539030582:web:92a82fa8499397ba0d9a97',
    messagingSenderId: '933539030582',
    projectId: 'sociality-8ed45',
    authDomain: 'sociality-8ed45.firebaseapp.com',
    storageBucket: 'sociality-8ed45.firebasestorage.app',
    measurementId: 'G-60CZRP7EPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-C0u_yomUNz30PN6xns3IzsRzaoz0Wmw',
    appId: '1:933539030582:android:1d6f206fbbc7c10f0d9a97',
    messagingSenderId: '933539030582',
    projectId: 'sociality-8ed45',
    storageBucket: 'sociality-8ed45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7c1bKRThd0pEBF5GbUf-ySO312l5l-n0',
    appId: '1:933539030582:ios:672a6c7ffbb5790b0d9a97',
    messagingSenderId: '933539030582',
    projectId: 'sociality-8ed45',
    storageBucket: 'sociality-8ed45.firebasestorage.app',
    iosBundleId: 'com.example.sociality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7c1bKRThd0pEBF5GbUf-ySO312l5l-n0',
    appId: '1:933539030582:ios:672a6c7ffbb5790b0d9a97',
    messagingSenderId: '933539030582',
    projectId: 'sociality-8ed45',
    storageBucket: 'sociality-8ed45.firebasestorage.app',
    iosBundleId: 'com.example.sociality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsW2O4Fd0rbHWQqhTM2Ft7bgeI7RLSG6M',
    appId: '1:933539030582:web:ea01d22279cff9ae0d9a97',
    messagingSenderId: '933539030582',
    projectId: 'sociality-8ed45',
    authDomain: 'sociality-8ed45.firebaseapp.com',
    storageBucket: 'sociality-8ed45.firebasestorage.app',
    measurementId: 'G-BQ553BQ66V',
  );
}
